%% TOTALS - First
x = -0.2651;
%% NO PAYLOAD NO OFFSET
momentTOTALROTORFORCES2_nopayload = momentROTORTHRUST2_nopayload(:,:,1)+momentROTORTHRUST2_nopayload(:,:,2)+ ...
                    momentROTORTHRUST2_nopayload(:,:,3)+momentROTORTHRUST2_nopayload(:,:,4)+ ...
                    momentROTORPx2_nopayload(:,:,1)+momentROTORPx2_nopayload(:,:,2)+ ...
                    momentROTORPx2_nopayload(:,:,3)+momentROTORPx2_nopayload(:,:,4)+ ...
                    momentROTORPy2_nopayload(:,:,1)+momentROTORPy2_nopayload(:,:,2)+ ...
                    momentROTORPy2_nopayload(:,:,3)+momentROTORPy2_nopayload(:,:,4);
                  
momentTOTALROTORMOMENTS2_nopayload = momentROTORMx2_nopayload(:,:,1)+momentROTORMx2_nopayload(:,:,2)+ ...
                    momentROTORMx2_nopayload(:,:,3)+momentROTORMx2_nopayload(:,:,4)+ ...
                    momentROTORMy2_nopayload(:,:,1)+momentROTORMy2_nopayload(:,:,2)+ ...
                    momentROTORMy2_nopayload(:,:,3)+momentROTORMy2_nopayload(:,:,4);
              
momentTOTALDRAG2_nopayload =  momentDRAGMOTOR2_nopayload(:,:,1)+momentDRAGMOTOR2_nopayload(:,:,2)+...
                   momentDRAGMOTOR2_nopayload(:,:,3)+momentDRAGMOTOR2_nopayload(:,:,4)+...
                   momentDRAGARM2_nopayload(:,:,1)+momentDRAGARM2_nopayload(:,:,2)+...
                   momentDRAGARM2_nopayload(:,:,3)+momentDRAGARM2_nopayload(:,:,4)+...
                   momentDRAGLEG2_nopayload(:,:,1)+momentDRAGLEG2_nopayload(:,:,2)+...
                   momentDRAGLEG2_nopayload(:,:,3)+momentDRAGLEG2_nopayload(:,:,4)+...
                   momentDRAGBODY2_nopayload(:,:)+momentDRAGPAYLOAD2_nopayload(:,:)+...
                   momentDRAGBODYinduced2_nopayload(:,:);

momentTOTALWEIGHTS2_nopayload = momentWEIGHTMOTOR2_nopayload(:,:,1)+momentWEIGHTMOTOR2_nopayload(:,:,2)+...
                   momentWEIGHTMOTOR2_nopayload(:,:,3)+momentWEIGHTMOTOR2_nopayload(:,:,4)+...
                   momentWEIGHTARM2_nopayload(:,:,1)+momentWEIGHTARM2_nopayload(:,:,2)+...
                   momentWEIGHTARM2_nopayload(:,:,3)+momentWEIGHTARM2_nopayload(:,:,4)+...
                   momentWEIGHTLEG2_nopayload(:,:,1)+momentWEIGHTLEG2_nopayload(:,:,2)+... 
                   momentWEIGHTLEG2_nopayload(:,:,3)+momentWEIGHTLEG2_nopayload(:,:,4)+...
                   momentWEIGHTBODY2_nopayload(:,:)+momentWEIGHTPAYLOAD2_nopayload(:,:)+momentWEIGHTOFFSET2_nopayload(:,:);

momentTOTALLIFTBODY2_nopayload = momentLIFTBODY2_nopayload(:,:);


%% WITH PAYLOAD NO OFFSET
% momentTOTALROTORFORCES2_withpayload = momentROTORTHRUST2_withpayload(:,:,1)+momentROTORTHRUST2_withpayload(:,:,2)+ ...
%                     momentROTORTHRUST2_withpayload(:,:,3)+momentROTORTHRUST2_withpayload(:,:,4)+ ...
%                     momentROTORPx2_withpayload(:,:,1)+momentROTORPx2_withpayload(:,:,2)+ ...
%                     momentROTORPx2_withpayload(:,:,3)+momentROTORPx2_withpayload(:,:,4)+ ...
%                     momentROTORPy2_withpayload(:,:,1)+momentROTORPy2_withpayload(:,:,2)+ ...
%                     momentROTORPy2_withpayload(:,:,3)+momentROTORPy2_withpayload(:,:,4);
%                   
% momentTOTALROTORMOMENTS2_withpayload = momentROTORMx2_withpayload(:,:,1)+momentROTORMx2_withpayload(:,:,2)+ ...
%                     momentROTORMx2_withpayload(:,:,3)+momentROTORMx2_withpayload(:,:,4)+ ...
%                     momentROTORMy2_withpayload(:,:,1)+momentROTORMy2_withpayload(:,:,2)+ ...
%                     momentROTORMy2_withpayload(:,:,3)+momentROTORMy2_withpayload(:,:,4);
%               
% momentTOTALDRAG2_withpayload =  momentDRAGMOTOR2_withpayload(:,:,1)+momentDRAGMOTOR2_withpayload(:,:,2)+...
%                    momentDRAGMOTOR2_withpayload(:,:,3)+momentDRAGMOTOR2_withpayload(:,:,4)+...
%                    momentDRAGARM2_withpayload(:,:,1)+momentDRAGARM2_withpayload(:,:,2)+...
%                    momentDRAGARM2_withpayload(:,:,3)+momentDRAGARM2_withpayload(:,:,4)+...
%                    momentDRAGLEG2_withpayload(:,:,1)+momentDRAGLEG2_withpayload(:,:,2)+...
%                    momentDRAGLEG2_withpayload(:,:,3)+momentDRAGLEG2_withpayload(:,:,4)+...
%                    momentDRAGBODY2_withpayload(:,:)+momentDRAGPAYLOAD2_withpayload(:,:)+...
%                    momentDRAGBODYinduced2_withpayload(:,:);
% 
% momentTOTALWEIGHTS2_withpayload = momentWEIGHTMOTOR2_withpayload(:,:,1)+momentWEIGHTMOTOR2_withpayload(:,:,2)+...
%                    momentWEIGHTMOTOR2_withpayload(:,:,3)+momentWEIGHTMOTOR2_withpayload(:,:,4)+...
%                    momentWEIGHTARM2_withpayload(:,:,1)+momentWEIGHTARM2_withpayload(:,:,2)+...
%                    momentWEIGHTARM2_withpayload(:,:,3)+momentWEIGHTARM2_withpayload(:,:,4)+...
%                    momentWEIGHTLEG2_withpayload(:,:,1)+momentWEIGHTLEG2_withpayload(:,:,2)+... 
%                    momentWEIGHTLEG2_withpayload(:,:,3)+momentWEIGHTLEG2_withpayload(:,:,4)+...
%                    momentWEIGHTBODY2_withpayload(:,:)+momentWEIGHTPAYLOAD2_withpayload(:,:)+momentWEIGHTOFFSET2_withpayload(:,:);
% 
% momentTOTALLIFTBODY2_withpayload = momentLIFTBODY2_withpayload(:,:);


%% NO PAYLOAD WITH OFFSET
momentTOTALROTORFORCES2_withoffset = momentROTORTHRUST2_withoffset(:,:,1)+momentROTORTHRUST2_withoffset(:,:,2)+ ...
                    momentROTORTHRUST2_withoffset(:,:,3)+momentROTORTHRUST2_withoffset(:,:,4)+ ...
                    momentROTORPx2_withoffset(:,:,1)+momentROTORPx2_withoffset(:,:,2)+ ...
                    momentROTORPx2_withoffset(:,:,3)+momentROTORPx2_withoffset(:,:,4)+ ...
                    momentROTORPy2_withoffset(:,:,1)+momentROTORPy2_withoffset(:,:,2)+ ...
                    momentROTORPy2_withoffset(:,:,3)+momentROTORPy2_withoffset(:,:,4);
                  
momentTOTALROTORMOMENTS2_withoffset = momentROTORMx2_withoffset(:,:,1)+momentROTORMx2_withoffset(:,:,2)+ ...
                    momentROTORMx2_withoffset(:,:,3)+momentROTORMx2_withoffset(:,:,4)+ ...
                    momentROTORMy2_withoffset(:,:,1)+momentROTORMy2_withoffset(:,:,2)+ ...
                    momentROTORMy2_withoffset(:,:,3)+momentROTORMy2_withoffset(:,:,4);
              
momentTOTALDRAG2_withoffset =  momentDRAGMOTOR2_withoffset(:,:,1)+momentDRAGMOTOR2_withoffset(:,:,2)+...
                   momentDRAGMOTOR2_withoffset(:,:,3)+momentDRAGMOTOR2_withoffset(:,:,4)+...
                   momentDRAGARM2_withoffset(:,:,1)+momentDRAGARM2_withoffset(:,:,2)+...
                   momentDRAGARM2_withoffset(:,:,3)+momentDRAGARM2_withoffset(:,:,4)+...
                   momentDRAGLEG2_withoffset(:,:,1)+momentDRAGLEG2_withoffset(:,:,2)+...
                   momentDRAGLEG2_withoffset(:,:,3)+momentDRAGLEG2_withoffset(:,:,4)+...
                   momentDRAGBODY2_withoffset(:,:)+momentDRAGPAYLOAD2_withoffset(:,:)+...
                   momentDRAGBODYinduced2_withoffset(:,:);

momentTOTALWEIGHTS2_withoffset = momentWEIGHTMOTOR2_withoffset(:,:,1)+momentWEIGHTMOTOR2_withoffset(:,:,2)+...
                   momentWEIGHTMOTOR2_withoffset(:,:,3)+momentWEIGHTMOTOR2_withoffset(:,:,4)+...
                   momentWEIGHTARM2_withoffset(:,:,1)+momentWEIGHTARM2_withoffset(:,:,2)+...
                   momentWEIGHTARM2_withoffset(:,:,3)+momentWEIGHTARM2_withoffset(:,:,4)+...
                   momentWEIGHTLEG2_withoffset(:,:,1)+momentWEIGHTLEG2_withoffset(:,:,2)+... 
                   momentWEIGHTLEG2_withoffset(:,:,3)+momentWEIGHTLEG2_withoffset(:,:,4)+...
                   momentWEIGHTBODY2_withoffset(:,:)+momentWEIGHTPAYLOAD2_withoffset(:,:)+momentWEIGHTOFFSET2_withoffset(:,:);

momentTOTALLIFTBODY2_withoffset = momentLIFTBODY2_withoffset(:,:);


%% RPM

% Rotor RPM (force trim only) vs airspeed
figure;
plot(flowV, rotorRPM2_nopayload(:,:,1),':ro', flowV, rotorRPM2_nopayload(:,:,2),':b+',...
    flowV, rotorRPM2_nopayload(:,:,3),':ks',flowV, rotorRPM2_nopayload(:,:,4),':gx',...
    flowV, rotorRPM2_withoffset(:,:,1),'-ro', flowV, rotorRPM2_withoffset(:,:,2),'-+',...
    flowV, rotorRPM2_withoffset(:,:,3),'-ks',flowV, rotorRPM2_withoffset(:,:,4),'-gx')
str1 = sprintf(' mass=%.2fkg ',massOFFSET);
str2 = sprintf(' x=%.2fm ',x);
fname = strcat('HAWK with ',str1,' at ',str2);
title(fname)
xlabel('Airspeed [m/s]')
ylabel('Rotor RPM')
legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right',...
    'Rotor 1 - Lead - Offset','Rotor 2 - Left - Offset','Rotor 3 - Rear - Offset','Rotor 4 - Right - Offset','Location','northwest')

%% MOMENTS

% Residual moments (force and moment trim) vs airspeed
% About y-axis only (pitch)
% Rotor Forces - Thrust, Px, Py
% Rotor Moments - Mx, My
% Drag - Dpar, Dind
% Lift - from body
% Weights - from components
figure;
plot(flowV, momentTOTALROTORFORCES2_nopayload(:,2),':b+',...
    flowV, momentTOTALROTORMOMENTS2_nopayload(:,2),':mo',...
    flowV, momentTOTALDRAG2_nopayload(:,2),':rs',...
    flowV, momentTOTALLIFTBODY2_nopayload(:,2),':kh',...
    flowV, momentTOTALWEIGHTS2_nopayload(:,2), ':gd',...
    flowV, momentTOTALROTORFORCES2_withoffset(:,2),'-b+',...
    flowV, momentTOTALROTORMOMENTS2_withoffset(:,2),'-mo',...
    flowV, momentTOTALDRAG2_withoffset(:,2),'-rs',...
    flowV, momentTOTALLIFTBODY2_withoffset(:,2),'-kh',...
    flowV, momentTOTALWEIGHTS2_withoffset(:,2), '-gd')
hold on
% plot (flowV, momentTOTAL2_nopayload(:,2), 'LineWidth',3,...
%     flowV, momentTOTAL2_withoffset(:,2), 'LineWidth',3)
str1 = sprintf(' mass=%.2fkg ',massOFFSET);
str2 = sprintf(' x=%.2fm ',x);
fname = strcat('HAWK with ',str1,' at ',str2);
title(fname)
xlabel('Airspeed [m/s]')
ylabel('Residual Moments [Nm]')
legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights',...
    'Rotor Forces - Offset','Rotor Moments - Offset','Drag - Offset','Lift - Offset','Weights - Offset',...'Total','Total - Offset',...
    'Location','southwest')



%% POWER

% Rotor Power (after moment trim) vs airspeed
figure;
plot(flowV, powerTOTAL2_nopayload(:,:,1),':ro', flowV, powerTOTAL2_nopayload(:,:,2),':b+',...
    flowV, powerTOTAL2_nopayload(:,:,3),':ks',flowV, powerTOTAL2_nopayload(:,:,4),':gx',...
    flowV, powerTOTAL2_withoffset(:,:,1),'-ro', flowV, powerTOTAL2_withoffset(:,:,2),'-b+',...
    flowV, powerTOTAL2_withoffset(:,:,3),'-ks',flowV, powerTOTAL2_withoffset(:,:,4),'-gx')
str1 = sprintf(' mass=%.2fkg ',massOFFSET);
str2 = sprintf(' x=%.2fm ',x);
fname = strcat('HAWK with ',str1,' at ',str2);
title(fname)
xlabel('Airspeed [m/s]')
ylabel('Rotor Power [W]')
legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right',...
    'Rotor 1 - Lead - Offset','Rotor 2 - Left - Offset','Rotor 3 - Rear - Offset','Rotor 4 - Right - Offset','Location','northwest')

% Total Power vs aispeed
figure;
plot(flowV, powerVEHICLE2_nopayload(:,1),flowV, powerVEHICLE2_withoffset(:,1))
str1 = sprintf(' mass=%.2fkg ',massOFFSET);
str2 = sprintf(' x=%.2fm ',x);
fname = strcat('HAWK with ',str1,' at ',str2);
title(fname)
xlabel('Airspeed [m/s]')
ylabel('Vehicle Power [W]')
legend('SkyRanger','SkyRanger with Offset','Location','northwest')
