%% TOTALS - First

momentTOTALROTORFORCES = momentROTORTHRUST(:,:,1)+momentROTORTHRUST(:,:,2)+ ...
                    momentROTORTHRUST(:,:,3)+momentROTORTHRUST(:,:,4)+ ...
                    momentROTORPx(:,:,1)+momentROTORPx(:,:,2)+ ...
                    momentROTORPx(:,:,3)+momentROTORPx(:,:,4)+ ...
                    momentROTORPy(:,:,1)+momentROTORPy(:,:,2)+ ...
                    momentROTORPy(:,:,3)+momentROTORPy(:,:,4);
                  
momentTOTALROTORMOMENTS = momentROTORMx(:,:,1)+momentROTORMx(:,:,2)+ ...
                    momentROTORMx(:,:,3)+momentROTORMx(:,:,4)+ ...
                    momentROTORMy(:,:,1)+momentROTORMy(:,:,2)+ ...
                    momentROTORMy(:,:,3)+momentROTORMy(:,:,4);
              
momentTOTALDRAG =  momentDRAGMOTOR(:,:,1)+momentDRAGMOTOR(:,:,2)+...
                   momentDRAGMOTOR(:,:,3)+momentDRAGMOTOR(:,:,4)+...
                   momentDRAGARM(:,:,1)+momentDRAGARM(:,:,2)+...
                   momentDRAGARM(:,:,3)+momentDRAGARM(:,:,4)+...
                   momentDRAGLEG(:,:,1)+momentDRAGLEG(:,:,2)+...
                   momentDRAGLEG(:,:,3)+momentDRAGLEG(:,:,4)+...
                   momentDRAGBODY(:,:)+momentDRAGPAYLOAD(:,:)+...
                   momentDRAGBODYinduced(:,:);

momentTOTALWEIGHTS = momentWEIGHTMOTOR(:,:,1)+momentWEIGHTMOTOR(:,:,2)+...
                   momentWEIGHTMOTOR(:,:,3)+momentWEIGHTMOTOR(:,:,4)+...
                   momentWEIGHTARM(:,:,1)+momentWEIGHTARM(:,:,2)+...
                   momentWEIGHTARM(:,:,3)+momentWEIGHTARM(:,:,4)+...
                   momentWEIGHTLEG(:,:,1)+momentWEIGHTLEG(:,:,2)+... 
                   momentWEIGHTLEG(:,:,3)+momentWEIGHTLEG(:,:,4)+...
                   momentWEIGHTBODY(:,:)+momentWEIGHTPAYLOAD(:,:)+momentWEIGHTOFFSET(:,:);

momentTOTALLIFTBODY = momentLIFTBODY(:,:);

% TESTmomentTOTAL = sum(momentTOTALROTORFORCES(:,1),momentTOTALROTORMOMENTS(:,1),momentTOTALDRAG(:,1),...
%     momentTOTALWEIGHTS(:,1),momentTOTALLIFTBODY(:,1));

%% LAST TOTALS
momentTOTALROTORFORCES2 = momentROTORTHRUST2(:,:,1)+momentROTORTHRUST2(:,:,2)+ ...
                    momentROTORTHRUST2(:,:,3)+momentROTORTHRUST2(:,:,4)+ ...
                    momentROTORPx2(:,:,1)+momentROTORPx2(:,:,2)+ ...
                    momentROTORPx2(:,:,3)+momentROTORPx2(:,:,4)+ ...
                    momentROTORPy2(:,:,1)+momentROTORPy2(:,:,2)+ ...
                    momentROTORPy2(:,:,3)+momentROTORPy2(:,:,4);
                  
momentTOTALROTORMOMENTS2 = momentROTORMx2(:,:,1)+momentROTORMx2(:,:,2)+ ...
                    momentROTORMx2(:,:,3)+momentROTORMx2(:,:,4)+ ...
                    momentROTORMy2(:,:,1)+momentROTORMy2(:,:,2)+ ...
                    momentROTORMy2(:,:,3)+momentROTORMy2(:,:,4);
              
momentTOTALDRAG2 =  momentDRAGMOTOR2(:,:,1)+momentDRAGMOTOR2(:,:,2)+...
                   momentDRAGMOTOR2(:,:,3)+momentDRAGMOTOR2(:,:,4)+...
                   momentDRAGARM2(:,:,1)+momentDRAGARM2(:,:,2)+...
                   momentDRAGARM2(:,:,3)+momentDRAGARM2(:,:,4)+...
                   momentDRAGLEG2(:,:,1)+momentDRAGLEG2(:,:,2)+...
                   momentDRAGLEG2(:,:,3)+momentDRAGLEG2(:,:,4)+...
                   momentDRAGBODY2(:,:)+momentDRAGPAYLOAD2(:,:)+...
                   momentDRAGBODYinduced2(:,:);

momentTOTALWEIGHTS2 = momentWEIGHTMOTOR2(:,:,1)+momentWEIGHTMOTOR2(:,:,2)+...
                   momentWEIGHTMOTOR2(:,:,3)+momentWEIGHTMOTOR2(:,:,4)+...
                   momentWEIGHTARM2(:,:,1)+momentWEIGHTARM2(:,:,2)+...
                   momentWEIGHTARM2(:,:,3)+momentWEIGHTARM2(:,:,4)+...
                   momentWEIGHTLEG2(:,:,1)+momentWEIGHTLEG2(:,:,2)+... 
                   momentWEIGHTLEG2(:,:,3)+momentWEIGHTLEG2(:,:,4)+...
                   momentWEIGHTBODY2(:,:)+momentWEIGHTPAYLOAD2(:,:)+momentWEIGHTOFFSET2(:,:);

momentTOTALLIFTBODY2 = momentLIFTBODY2(:,:);

%% GRADIENTS
% First Run
for j = 1:1:countV
     if j>1                             

            gradmomentFORCES(j,1)            = momentTOTALROTORFORCES(j,1) - momentTOTALROTORFORCES(j-1,1);
            gradmomentMOMENTS(j,1)           = momentTOTALROTORMOMENTS(j,1) - momentTOTALROTORMOMENTS(j-1,1);
            gradmomentDRAG(j,1)              = momentTOTALDRAG(j,1) - momentTOTALDRAG(j-1,1);
            gradmomentWEIGHTS(j,1)           = momentTOTALWEIGHTS(j,1) - momentTOTALWEIGHTS(j-1,1);
            gradmomentLIFT(j,1)              = momentLIFTBODY(j,1) - momentLIFTBODY(j-1,1);
            gradmomentTOTAL(j,1)             = momentTOTAL(j,1) - momentTOTAL(j-1,1); 

     else
            gradmomentFORCES(j,1)            = 0;
            gradmomentMOMENTS(j,1)           = 0;
            gradmomentDRAG(j,1)              = 0;
            gradmomentWEIGHTS(j,1)           = 0;
            gradmomentLIFT(j,1)              = 0;
            gradmomentTOTAL(j,1)             = 0;

     end
end

% Last Run
for j = 1:1:countV
     if j>1                             

            gradmomentFORCES2(j,1)            = momentTOTALROTORFORCES2(j,1) - momentTOTALROTORFORCES2(j-1,1);
            gradmomentMOMENTS2(j,1)           = momentTOTALROTORMOMENTS2(j,1) - momentTOTALROTORMOMENTS2(j-1,1);
            gradmomentDRAG2(j,1)              = momentTOTALDRAG2(j,1) - momentTOTALDRAG2(j-1,1);
            gradmomentWEIGHTS2(j,1)           = momentTOTALWEIGHTS2(j,1) - momentTOTALWEIGHTS2(j-1,1);
            gradmomentLIFT2(j,1)              = momentLIFTBODY2(j,1) - momentLIFTBODY2(j-1,1);
            gradmomentTOTAL2(j,1)             = momentTOTAL2(j,1) - momentTOTAL2(j-1,1); 
            
     else
            gradmomentFORCES2(j,1)            = 0;
            gradmomentMOMENTS2(j,1)           = 0;
            gradmomentDRAG2(j,1)              = 0;
            gradmomentWEIGHTS2(j,1)           = 0;
            gradmomentLIFT2(j,1)              = 0;
            gradmomentTOTAL2(j,1)             = 0;

     end
end


%% ROLL MOMENTS
% % Residual moments (force trim only) vs airspeed
% % About y-axis only (pitch)
% % Rotor Forces - Thrust, Px, Py
% % Rotor Moments - Mx, My
% % Drag - Dpar, Dind
% % Lift - from body
% % Weights - from components
% figure;
% plot(flowV, momentTOTALROTORFORCES(:,1),'--b+',...
%     flowV, momentTOTALROTORMOMENTS(:,1),'--ro',...
%     flowV, momentTOTALDRAG(:,1),':rs',...
%     flowV, momentTOTALLIFTBODY(:,1),'-.kh',...
%     flowV, momentTOTALWEIGHTS(:,1), '-gd')
% hold on
% plot (flowV, momentTOTAL(:,1), 'LineWidth',2)
% title('Residual Moments vs Airspeed (Force Trim Only)')
% legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')
% 
% 
% 
% 
% 
% % Residual moments (force and moment trim) vs airspeed
% % About y-axis only (pitch)
% % Rotor Forces - Thrust, Px, Py
% % Rotor Moments - Mx, My
% % Drag - Dpar, Dind
% % Lift - from body
% % Weights - from components
% figure;
% plot(flowV, momentTOTALROTORFORCES2(:,1),'--b+',...
%     flowV, momentTOTALROTORMOMENTS2(:,1),'--ro',...
%     flowV, momentTOTALDRAG2(:,1),':rs',...
%     flowV, momentTOTALLIFTBODY2(:,1),'-.kh',...
%     flowV, momentTOTALWEIGHTS2(:,1), '-gd')
% hold on
% plot (flowV, momentTOTAL2(:,1), 'LineWidth',2)
% title('Residual Moments vs Airspeed (Force and Moment Trim)')
% legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')


% % Gradients of residual moments (force trim only) vs airspeed
% % About y-axis only (pitch)
% % Rotor Forces - Thrust, Px, Py
% % Rotor Moments - Mx, My
% % Drag - Dpar, Dind
% % Lift - from body
% % Weights - from components
% figure;
% plot(flowV, gradmomentFORCES(:,1),'--b+',...
%     flowV, gradmomentMOMENTS(:,1),'--ro',...
%     flowV, gradmomentDRAG(:,1),':rs',...
%     flowV, gradmomentLIFT(:,1),'-.kh',...
%     flowV, gradmomentWEIGHTS(:,1), '-gd')
% hold on
% plot (flowV, gradmomentTOTAL(:,1), 'LineWidth',2)
% title('Gradients of Residual Moments vs Airspeed (Force Trim Only)')
% legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')
% 
% % Gradients of residual moments (force and moment trim) vs airspeed
% % About y-axis only (pitch)
% % Rotor Forces - Thrust, Px, Py
% % Rotor Moments - Mx, My
% % Drag - Dpar, Dind
% % Lift - from body
% % Weights - from components
% figure;
% plot(flowV, gradmomentFORCES2(:,1),'--b+',...
%     flowV, gradmomentMOMENTS2(:,1),'--ro',...
%     flowV, gradmomentDRAG2(:,1),':rs',...
%     flowV, gradmomentLIFT2(:,1),'-.kh',...
%     flowV, gradmomentWEIGHTS2(:,1), '-gd')
% hold on
% plot (flowV, gradmomentTOTAL2(:,1), 'LineWidth',2)
% title('Gradients of Residual Moments vs Airspeed (Force and Moment Trim)')
% legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')


%% PLOTS flowV
% % Residual moments (force trim only) vs airspeed
% % About y-axis only (pitch)
% % Rotor Forces - Thrust, Px, Py
% % Rotor Moments - Mx, My
% % Drag - Dpar, Dind
% % Lift - from body
% % Weights - from components
% figure;
% plot(flowV, momentTOTALROTORFORCES(:,2),'--b+',...
%     flowV, momentTOTALROTORMOMENTS(:,2),'--mo',...
%     flowV, momentTOTALDRAG(:,2),':rs',...
%     flowV, momentTOTALLIFTBODY(:,2),'-.kh',...
%     flowV, momentTOTALWEIGHTS(:,2), '-gd')
% hold on
% plot (flowV, momentTOTAL(:,2), 'LineWidth',2)
% title('Residual Moments vs Airspeed (Force Trim Only)')
% legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')
% 
% 
% % % Residual moments (force trim only) vs airspeed
% % % About y-axis only (pitch)
% % % Rotor Forces - Thrust, Px, Py
% % % Rotor Moments - Mx, My
% % % Drag - Dpar, Dind
% % % Lift - from body
% % % Weights - from components
% % figure;
% % plot(flowV, momentROTORTHRUST(:,2,1),'b+',...
% %      flowV, momentROTORTHRUST(:,2,2),'bo',...
% %      flowV, momentROTORTHRUST(:,2,3),'bs',...
% %      flowV, momentROTORTHRUST(:,2,4),'b^',...
% %      flowV, momentROTORPx(:,2,1),'--b+',...
% %      flowV, momentROTORPx(:,2,2),'--bo',...
% %      flowV, momentROTORPx(:,2,3),'--bs',...
% %      flowV, momentROTORPx(:,2,4),'--b^',...
% %      flowV, momentROTORMy(:,2,1),'--m+',...
% %      flowV, momentROTORMy(:,2,2),'--mo',...
% %      flowV, momentROTORMy(:,2,3),'--ms',...
% %      flowV, momentROTORMy(:,2,4),'--m^',...
% %      flowV, momentDRAGARM(:,2,1),'-.r+',...
% %      flowV, momentDRAGARM(:,2,2),'-.ro',...
% %      flowV, momentDRAGARM(:,2,3),'-.rs',...
% %      flowV, momentDRAGARM(:,2,4),'-.r^',...
% %      flowV, momentDRAGMOTOR(:,2,1),'--r+',...
% %      flowV, momentDRAGMOTOR(:,2,2),'--ro',...
% %      flowV, momentDRAGMOTOR(:,2,3),'--rs',...
% %      flowV, momentDRAGMOTOR(:,2,4),'--r^',...
% %      flowV, momentDRAGLEG(:,2,1),'r+',...
% %      flowV, momentDRAGLEG(:,2,2),'ro',...
% %      flowV, momentDRAGLEG(:,2,3),'rs',...
% %      flowV, momentDRAGLEG(:,2,4),'r^',...
% %      flowV, momentDRAGBODY(:,2),':rs',...
% %      flowV, momentDRAGBODYinduced(:,2),':ro',...
% %      flowV, momentDRAGPAYLOAD(:,2),':r+',... 
% %     flowV, momentLIFTBODY(:,2),'-.kh',...
% %     flowV, momentWEIGHTARM(:,2,1),'-.g+',...
% %      flowV, momentWEIGHTARM(:,2,2),'-.go',...
% %      flowV, momentWEIGHTARM(:,2,3),'-.gs',...
% %      flowV, momentWEIGHTARM(:,2,4),'-.g^',...
% %      flowV, momentWEIGHTMOTOR(:,2,1),'--g+',...
% %      flowV, momentWEIGHTMOTOR(:,2,2),'--go',...
% %      flowV, momentWEIGHTMOTOR(:,2,3),'--gs',...
% %      flowV, momentWEIGHTMOTOR(:,2,4),'--g^',...
% %      flowV, momentWEIGHTLEG(:,2,1),'g+',...
% %      flowV, momentWEIGHTLEG(:,2,2),'go',...
% %      flowV, momentWEIGHTLEG(:,2,3),'gs',...
% %      flowV, momentWEIGHTLEG(:,2,4),'g^',...
% %      flowV, momentWEIGHTBODY(:,2),':gs',...
% %      flowV, momentWEIGHTPAYLOAD(:,2),':g+')      
% % hold on
% % plot (flowV, momentTOTAL(:,2), 'LineWidth',2)
% % title('Residual Moments vs Airspeed (Force Trim Only)')
% % legend('Thrust - R1', 'Thrust - R2','Thrust - R3','Thrust - R4',...
% %     'Px - R1','Px - R2','Px - R3','Px - R4',...
% %     'My - R1','My - R2','My - R3','My - R4',...
% %     'DRAG ARM - 1','DRAG ARM - 2','DRAG ARM - 3','DRAG ARM - 4',...
% %     'DRAG MOTOR - 1','DRAG MOTOR - 2','DRAG MOTOR - 3','DRAG MOTOR - 4',...
% %     'DRAG LEG - 1','DRAG LEG - 2','DRAG LEG - 3','DRAG LEG - 4',...
% %     'DRAG BODY','INDUCED DRAG BODY','DRAG PAYLOAD','LIFT BODY',...    
% %     'WEIGHT ARM - 1','WEIGHT ARM - 2','WEIGHT ARM - 3','WEIGHT ARM - 4',...
% %     'WEIGHT MOTOR - 1','WEIGHT MOTOR - 2','WEIGHT MOTOR - 3','WEIGHT MOTOR - 4',...
% %     'WEIGHT LEG - 1','WEIGHT LEG - 2','WEIGHT LEG - 3','WEIGHT LEG - 4',...
% %     'WEIGHT BODY','WEIGHT PAYLOAD',...
% % 'Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')
% 
% 
% figure;
% plot(flowV, momentROTORTHRUST(:,2,1),'b+',...
%      flowV, momentROTORTHRUST(:,2,2),'bo',...
%      flowV, momentROTORTHRUST(:,2,3),'bs',...
%      flowV, momentROTORTHRUST(:,2,4),'b^',...
%     flowV, momentROTORPx(:,2,1),'--b+',...
%      flowV, momentROTORPx(:,2,2),'--bo',...
%      flowV, momentROTORPx(:,2,3),'--bs',...
%      flowV, momentROTORPx(:,2,4),'--b^',...
%     flowV, momentROTORMy(:,2,1),'--m+',...
%      flowV, momentROTORMy(:,2,2),'--mo',...
%      flowV, momentROTORMy(:,2,3),'--ms',...
%      flowV, momentROTORMy(:,2,4),'--m^',...
%     flowV, momentDRAGARM(:,2,1)+momentDRAGARM(:,2,2)+momentDRAGARM(:,2,3)+momentDRAGARM(:,2,4),'-.r+',...
%      flowV, momentDRAGMOTOR(:,2,1)+momentDRAGMOTOR(:,2,2)+momentDRAGMOTOR(:,2,3)+momentDRAGMOTOR(:,2,4),'-.ro',...
%      flowV, momentDRAGLEG(:,2,1)+momentDRAGLEG(:,2,2)+momentDRAGLEG(:,2,3)+momentDRAGLEG(:,2,4),'-.rs',...
%     flowV, momentDRAGBODY(:,2),':rs',...
%      flowV, momentDRAGBODYinduced(:,2),':ro',...
%      flowV, momentDRAGPAYLOAD(:,2),':r+',... 
%     flowV, momentLIFTBODY(:,2),'-.kh',...
%     flowV, momentWEIGHTARM(:,2,1)+momentWEIGHTARM(:,2,2)+momentWEIGHTARM(:,2,3)+momentWEIGHTARM(:,2,4),'-.g+',...
%      flowV, momentWEIGHTMOTOR(:,2,1)+momentWEIGHTMOTOR(:,2,2)+momentWEIGHTMOTOR(:,2,3)+momentWEIGHTMOTOR(:,2,4),'-.go',...
%      flowV, momentWEIGHTLEG(:,2,1)+momentWEIGHTLEG(:,2,2)+momentWEIGHTLEG(:,2,3)+momentWEIGHTLEG(:,2,4),'-.gs',...
%     flowV, momentWEIGHTBODY(:,2),':gs',...
%     flowV, momentWEIGHTPAYLOAD(:,2),':g+')      
% hold on
% plot (flowV, momentTOTAL(:,2), 'LineWidth',2)
% title('Residual Moments vs Airspeed (Force Trim Only)')
% legend('Thrust - R1', 'Thrust - R2','Thrust - R3','Thrust - R4',...
%     'Px - R1','Px - R2','Px - R3','Px - R4',...
%     'My - R1','My - R2','My - R3','My - R4',...
%     'ARMS - TOTAL DRAG','MOTORS - TOTAL DRAG','LEGS - TOTAL DRAG',...
%     'DRAG BODY','INDUCED DRAG BODY','DRAG PAYLOAD','LIFT BODY',...    
%     'ARMS - TOTAL WEIGHT','MOTORS - TOTAL WEIGHT','LEGS - TOTAL WEIGHT',...
%     'WEIGHT BODY','WEIGHT PAYLOAD','southwest')
% 
% 
% 
% 
% 
% 
% 
% % Residual moments (force and moment trim) vs airspeed
% % About y-axis only (pitch)
% % Rotor Forces - Thrust, Px, Py
% % Rotor Moments - Mx, My
% % Drag - Dpar, Dind
% % Lift - from body
% % Weights - from components
% figure;
% plot(flowV, momentTOTALROTORFORCES2(:,2),'--b+',...
%     flowV, momentTOTALROTORMOMENTS2(:,2),'--ro',...
%     flowV, momentTOTALDRAG2(:,2),':rs',...
%     flowV, momentTOTALLIFTBODY2(:,2),'-.kh',...
%     flowV, momentTOTALWEIGHTS2(:,2), '-gd')
% hold on
% plot (flowV, momentTOTAL2(:,2), 'LineWidth',2)
% title('Residual Moments vs Airspeed (Force and Moment Trim)')
% legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')
% 
% % Rotor thrust (force trim only) vs airspeed
% figure;
% plot(flowV, rotorTHRUST(:,:,1), flowV, rotorTHRUST(:,:,2),...
%     flowV, rotorTHRUST(:,:,3),flowV, rotorTHRUST(:,:,4))
% title('Rotor Thrust vs Airspeed (Force Trim Only)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% 
% % Rotor thrust (after moment trim) vs airspeed
% figure;
% plot(flowV, rotorTHRUST2(:,:,1), flowV, rotorTHRUST2(:,:,2),...
%     flowV, rotorTHRUST2(:,:,3),flowV, rotorTHRUST2(:,:,4))
% title('Rotor Thrust vs Airspeed (Force and Moment Trim)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% % Rotor RPM (force trim only) vs airspeed
% figure;
% plot(flowV, rotorRPM(:,:,1), flowV, rotorRPM(:,:,2),...
%     flowV, rotorRPM(:,:,3),flowV, rotorRPM(:,:,4))
% title('Rotor RPM vs Airspeed (Force Trim Only)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% % Rotor RPM (after moment trim) vs airspeed
% figure;
% plot(flowV, rotorRPM2(:,:,1), flowV, rotorRPM2(:,:,2),...
%     flowV, rotorRPM2(:,:,3),flowV, rotorRPM2(:,:,4))
% title('Rotor RPM vs Airspeed (Force and Moment Trim)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% % Rotor Power (force trim only) vs airspeed
% figure;
% plot(flowV, powerTOTAL(:,:,1), flowV, powerTOTAL(:,:,2),...
%     flowV, powerTOTAL(:,:,3),flowV, powerTOTAL(:,:,4))
% title('Rotor Power vs Airspeed (Force Trim Only)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% % Rotor Power (after moment trim) vs airspeed
% figure;
% plot(flowV, powerTOTAL2(:,:,1), flowV, powerTOTAL2(:,:,2),...
%     flowV, powerTOTAL2(:,:,3),flowV, powerTOTAL2(:,:,4))
% title('Total Rotor Power vs Airspeed (Force and Moment Trim)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% % Total Power vs aispeed
% figure;
% plot(flowV, powerVEHICLE(:,1), flowV, powerVEHICLE2(:,1))
% title('Total Vehicle Power vs Airspeed (Force and Moment Trim)')
% legend('Force Trim Only','Moment and Force Trim','Location','northwest')
% 
% 
% % % Gradients of residual moments (force trim only) vs airspeed
% % % About y-axis only (pitch)
% % % Rotor Forces - Thrust, Px, Py
% % % Rotor Moments - Mx, My
% % % Drag - Dpar, Dind
% % % Lift - from body
% % % Weights - from components
% % figure;
% % plot(flowV, gradmomentFORCES(:,2),'--b+',...
% %     flowV, gradmomentMOMENTS(:,2),'--ro',...
% %     flowV, gradmomentDRAG(:,2),':rs',...
% %     flowV, gradmomentLIFT(:,2),'-.kh',...
% %     flowV, gradmomentWEIGHTS(:,2), '-gd')
% % hold on
% % plot (flowV, gradmomentTOTAL(:,2), 'LineWidth',2)
% % title('Gradients of Residual Moments vs Airspeed (Force Trim Only)')
% % legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')
% 
% 
% % % Gradients of residual moments (force and moment trim) vs airspeed
% % % About y-axis only (pitch)
% % % Rotor Forces - Thrust, Px, Py
% % % Rotor Moments - Mx, My
% % % Drag - Dpar, Dind
% % % Lift - from body
% % % Weights - from components
% % figure;
% % plot(flowV, gradmomentFORCES2(:,2),'--b+',...
% %     flowV, gradmomentMOMENTS2(:,2),'--ro',...
% %     flowV, gradmomentDRAG2(:,2),':rs',...
% %     flowV, gradmomentLIFT2(:,2),'-.kh',...
% %     flowV, gradmomentWEIGHTS2(:,2), '-gd')
% % hold on
% % plot (flowV, gradmomentTOTAL2(:,2), 'LineWidth',2)
% % title('Gradients of Residual Moments vs Airspeed (Force and Moment Trim)')
% % legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')
% 
% 
% % Interference through rotors by rotors ONLY
% figure;
% plot(flowV, vi_int(:,3,1),'--b+',...
%     flowV, vi_int(:,3,2),'--ro',...
%     flowV, vi_int(:,3,3),':rs',...
%     flowV, vi_int(:,3,4),'-gd')
% 
% % Body interference downward
% figure;
% plot(flowV, vi_body(:,3,1),'--b+',...
%     flowV, vi_body(:,3,2),'--ro',...
%     flowV, vi_body(:,3,3),':rs',...
%     flowV, vi_body(:,3,4),'-gd')
% 
% figure;
% plot(flowV, rotorVelINFLOW(:,1,1),'--b+',...
%     flowV, rotorVelINFLOW(:,1,2),'--ro',...
%     flowV, rotorVelINFLOW(:,1,3),':rs',...
%     flowV, rotorVelINFLOW(:,1,4),'-gd')
% %z
% figure;
% plot(flowV, vi_int_total(:,3,1),'--b+',...
%     flowV, vi_int_total(:,3,2),'--ro',...
%     flowV, vi_int_total(:,3,3),':rs',...
%     flowV, vi_int_total(:,3,4),'-gd')
% %x
% figure;
% plot(flowV, vi_int_total(:,1,1),'--b+',...
%     flowV, vi_int_total(:,1,2),'--ro',...
%     flowV, vi_int_total(:,1,3),':rs',...
%     flowV, vi_int_total(:,1,4),'-gd')
% 
% mag_vi_int_total = sqrt(sum(abs(vi_int_total).^2,2));
% 
% % %mag
% % figure;
% % plot(flowV, mag_vi_int_total(:,1,1),'--b+',...
% %     flowV, mag_vi_int_total(:,1,2),'--ro',...
% %     flowV, mag_vi_int_total(:,1,3),':rs',...
% %     flowV, mag_vi_int_total(:,1,4),'-gd')


%% PLOTS pitch 
% 
% % Residual moments (force trim only) vs airspeed
% % About y-axis only (pitch)
% % Rotor Forces - Thrust, Px, Py
% % Rotor Moments - Mx, My
% % Drag - Dpar, Dind
% % Lift - from body
% % Weights - from components
% figure;
% plot(pitchVEHICLEdeg, momentTOTALROTORFORCES,'--b+',...
%     pitchVEHICLEdeg, momentTOTALROTORMOMENTS,'--ro',...
%     pitchVEHICLEdeg, momentTOTALDRAG,':rs',...
%     pitchVEHICLEdeg, momentTOTALLIFTBODY,'-.kh',...
%     pitchVEHICLEdeg, momentTOTALWEIGHTS, '-gd')
% hold on
% plot (pitchVEHICLEdeg, momentTOTAL(:,2), 'LineWidth',2)
% title('Residual Moments vs Airspeed (Force Trim Only)')
% legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')
% 
% % Residual moments (force and moment trim) vs airspeed
% % About y-axis only (pitch)
% % Rotor Forces - Thrust, Px, Py
% % Rotor Moments - Mx, My
% % Drag - Dpar, Dind
% % Lift - from body
% % Weights - from components
% figure;
% plot(pitchVEHICLEdeg, momentTOTALROTORFORCES2,'--b+',...
%     pitchVEHICLEdeg, momentTOTALROTORMOMENTS2,'--ro',...
%     pitchVEHICLEdeg, momentTOTALDRAG2,':rs',...
%     pitchVEHICLEdeg, momentTOTALLIFTBODY2,'-.kh',...
%     pitchVEHICLEdeg, momentTOTALWEIGHTS2, '-gd')
% hold on
% plot (pitchVEHICLEdeg, momentTOTAL2(:,2), 'LineWidth',2)
% title('Residual Moments vs Airspeed (Force and Moment Trim)')
% legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')
% 
% % Rotor thrust (after moment trim) vs airspeed
% figure;
% plot(pitchVEHICLEdeg, rotorTHRUST2(:,:,1), pitchVEHICLEdeg, rotorTHRUST2(:,:,2),...
%     pitchVEHICLEdeg, rotorTHRUST2(:,:,3),pitchVEHICLEdeg, rotorTHRUST2(:,:,4))
% title('Rotor Thrust vs Airspeed (Force and Moment Trim)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% % Rotor RPM (force trim only) vs airspeed
% figure;
% plot(pitchVEHICLEdeg, rotorRPM(:,:,1), pitchVEHICLEdeg, rotorRPM(:,:,2),...
%     pitchVEHICLEdeg, rotorRPM(:,:,3),pitchVEHICLEdeg, rotorRPM(:,:,4))
% title('Rotor RPM vs Airspeed (Force Trim Only)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% % Rotor RPM (after moment trim) vs airspeed
% figure;
% plot(pitchVEHICLEdeg, rotorRPM2(:,:,1), pitchVEHICLEdeg, rotorRPM2(:,:,2),...
%     pitchVEHICLEdeg, rotorRPM2(:,:,3),pitchVEHICLEdeg, rotorRPM2(:,:,4))
% title('Rotor RPM vs Airspeed (Force and Moment Trim)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% % Rotor Power (force trim only) vs airspeed
% figure;
% plot(pitchVEHICLEdeg, powerTOTAL(:,:,1), pitchVEHICLEdeg, powerTOTAL(:,:,2),...
%     pitchVEHICLEdeg, powerTOTAL(:,:,3),pitchVEHICLEdeg, powerTOTAL(:,:,4))
% title('Rotor Power vs Airspeed (Force Trim Only)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% % Rotor Power (after moment trim) vs airspeed
% figure;
% plot(pitchVEHICLEdeg, powerTOTAL2(:,:,1), pitchVEHICLEdeg, powerTOTAL2(:,:,2),...
%     pitchVEHICLEdeg, powerTOTAL2(:,:,3),pitchVEHICLEdeg, powerTOTAL2(:,:,4))
% title('Total Rotor Power vs Airspeed (Force and Moment Trim)')
% legend('Rotor 1 - Lead','Rotor 2 - Left','Rotor 3 - Rear','Rotor 4 - Right','Location','northwest')
% 
% % Total Power vs aispeed
% figure;
% plot(pitchVEHICLEdeg, powerVEHICLE(:,1), pitchVEHICLEdeg, powerVEHICLE2(:,1))
% title('Total Vehicle Power vs Airspeed (Force and Moment Trim)')
% legend('Force Trim Only','Moment and Force Trim','Location','northwest')
% 
% 
% % Gradients of residual moments (force trim only) vs airspeed
% % About y-axis only (pitch)
% % Rotor Forces - Thrust, Px, Py
% % Rotor Moments - Mx, My
% % Drag - Dpar, Dind
% % Lift - from body
% % Weights - from components
% figure;
% plot(pitchVEHICLEdeg, gradmomentFORCES,'--b+',...
%     pitchVEHICLEdeg, gradmomentMOMENTS,'--ro',...
%     pitchVEHICLEdeg, gradmomentDRAG,':rs',...
%     pitchVEHICLEdeg, gradmomentLIFT,'-.kh',...
%     pitchVEHICLEdeg, gradmomentWEIGHTS, '-gd')
% hold on
% plot (pitchVEHICLEdeg, gradmomentTOTAL(:,2), 'LineWidth',2)
% title('Gradients of Residual Moments vs Airspeed (Force Trim Only)')
% legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')
% 
% % Gradients of residual moments (force and moment trim) vs airspeed
% % About y-axis only (pitch)
% % Rotor Forces - Thrust, Px, Py
% % Rotor Moments - Mx, My
% % Drag - Dpar, Dind
% % Lift - from body
% % Weights - from components
% figure;
% plot(pitchVEHICLEdeg, gradmomentFORCES2,'--b+',...
%     pitchVEHICLEdeg, gradmomentMOMENTS2,'--ro',...
%     pitchVEHICLEdeg, gradmomentDRAG2,':rs',...
%     pitchVEHICLEdeg, gradmomentLIFT2,'-.kh',...
%     pitchVEHICLEdeg, gradmomentWEIGHTS2, '-gd')
% hold on
% plot (pitchVEHICLEdeg, gradmomentTOTAL2(:,2), 'LineWidth',2)
% title('Gradients of Residual Moments vs Airspeed (Force and Moment Trim)')
% legend('Rotor Forces','Rotor Moments','Drag','Lift','Weights','Total','Location','southwest')

%% PLOTS VR and WAKES

% VR - rotorVelINFLOW - resultant rotor velocity
figure;
plot(flowV, flowV-flowV,'k',...
    flowV,flowV - rotorVelINFLOW(:,:,1),'-ro',...
    flowV,flowV - rotorVelINFLOW(:,:,2),'-b+',...
    flowV,flowV - rotorVelINFLOW(:,:,3),'-ks',...
    flowV,flowV - rotorVelINFLOW(:,:,4),'-gx')

hold on
plot(flowV, flowV-flowV,'k',...
    flowV,flowV - rotorVelINFLOW2(:,:,1),'-.ro',...
    flowV,flowV - rotorVelINFLOW2(:,:,2),'-.b+',...
    flowV,flowV - rotorVelINFLOW2(:,:,3),'-.ks',...
    flowV,flowV - rotorVelINFLOW2(:,:,4),'-.gx')

%% Percentage of total inflow velocity by freestream velocity
% Force Trim Only
figure;
plot(flowV, flowV./flowV,'k',...
    flowV,rotorVelINFLOW(:,:,1)./flowV ,'-ro',...
    flowV,rotorVelINFLOW(:,:,2)./flowV,'-b+',...
    flowV,rotorVelINFLOW(:,:,3)./flowV,'-ks',...
    flowV,rotorVelINFLOW(:,:,4)./flowV,'-gx')

%After Moment Trim
hold on
plot(flowV, flowV./flowV,'k',...
    flowV,rotorVelINFLOW2(:,:,1)./flowV,'-.ro',...
    flowV,rotorVelINFLOW2(:,:,2)./flowV,'-.b+',...
    flowV,rotorVelINFLOW2(:,:,3)./flowV,'-.ks',...
    flowV,rotorVelINFLOW2(:,:,4)./flowV,'-.gx')
hold off
%%
figure;
plot(pitchVEHICLEdeg, flowV./flowV,'k',...
    pitchVEHICLEdeg,rotorVelINFLOW(:,:,1)./flowV ,'-ro',...
    pitchVEHICLEdeg,rotorVelINFLOW(:,:,2)./flowV,'-b+',...
    pitchVEHICLEdeg,rotorVelINFLOW(:,:,3)./flowV,'-ks',...
    pitchVEHICLEdeg,rotorVelINFLOW(:,:,4)./flowV,'-gx')

%After Moment Trim
hold on
plot(pitchVEHICLEdeg, flowV./flowV,'k',...
    pitchVEHICLEdeg,rotorVelINFLOW2(:,:,1)./flowV,'-.ro',...
    pitchVEHICLEdeg,rotorVelINFLOW2(:,:,2)./flowV,'-.b+',...
    pitchVEHICLEdeg,rotorVelINFLOW2(:,:,3)./flowV,'-.ks',...
    pitchVEHICLEdeg,rotorVelINFLOW2(:,:,4)./flowV,'-.gx')
hold off

%%

FREE = [flowV zeros(length(flowV),1) zeros(length(flowV),1)]
FREEplusINT = FREE + vi_z;
VR_INT = sqrt(sum(abs(FREEplusINT).^2,2))
FREEplusINTplusBODY = FREEplusINT + vi_body;
VR_INT_BODY = sqrt(sum(abs(FREEplusINTplusBODY).^2,2))

figure;
plot(pitchVEHICLEdeg, flowV./flowV,'k',...
    pitchVEHICLEdeg,VR_INT(:,:,1)./flowV ,'-ro',...
    pitchVEHICLEdeg,VR_INT(:,:,2)./flowV,'-b+',...
    pitchVEHICLEdeg,VR_INT(:,:,3)./flowV,'-ks',...
    pitchVEHICLEdeg,VR_INT(:,:,4)./flowV,'-gx')

%After Moment Trim
hold on
plot(pitchVEHICLEdeg, flowV./flowV,'k',...
    pitchVEHICLEdeg,VR_INT_BODY(:,:,1)./flowV,'-.ro',...
    pitchVEHICLEdeg,VR_INT_BODY(:,:,2)./flowV,'-.b+',...
    pitchVEHICLEdeg,VR_INT_BODY(:,:,3)./flowV,'-.ks',...
    pitchVEHICLEdeg,VR_INT_BODY(:,:,4)./flowV,'-.gx')

hold on
plot(pitchVEHICLEdeg, flowV./flowV,'k',...
    pitchVEHICLEdeg,rotorVelINFLOW(:,:,1)./flowV ,'--ro',...
    pitchVEHICLEdeg,rotorVelINFLOW(:,:,2)./flowV,'--b+',...
    pitchVEHICLEdeg,rotorVelINFLOW(:,:,3)./flowV,'--ks',...
    pitchVEHICLEdeg,rotorVelINFLOW(:,:,4)./flowV,'--gx')
hold off




%% vi_int z-component only rotated by pitch
% Percentage of mutual interference by freestream

figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_z(:,3,1)./flowV,'--ro',...
    flowV,vi_z(:,3,2)./flowV,'--b+',...
    flowV,vi_z(:,3,3)./flowV,'--ks',...
    flowV,vi_z(:,3,4)./flowV,'--gx')
title('vi_z,z/Vinf - Normal Induced Velocity in Z-Direction Global/Freestream Velocity')

figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_z(:,1,1)./flowV,'-.ro',...
    flowV,vi_z(:,1,2)./flowV,'-.b+',...
    flowV,vi_z(:,1,3)./flowV,'-.ks',...
    flowV,vi_z(:,1,4)./flowV,'-.gx')
title('vi_z,x/Vinf - Normal Induced Velocity in X-Direction Global/Freestream Velocity')

figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_z(:,2,1)./flowV,'-.ro',...
    flowV,vi_z(:,2,2)./flowV,'-.b+',...
    flowV,vi_z(:,2,3)./flowV,'-.ks',...
    flowV,vi_z(:,2,4)./flowV,'-.gx')
title('vi_z,y/Vinf - Normal Induced Velocity in Y-Direction Global/Freestream Velocity')


figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,sqrt(sum(abs(vi_z(:,:,1))^2,2))./flowV,'-.ro',...
    flowV,vi_z(:,:,2)./flowV,'-.b+',...
    flowV,vi_z(:,:,3)./flowV,'-.ks',...
    flowV,vi_z(:,:,4)./flowV,'-.gx')


%% vi_body
figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_body(:,3,1)./flowV,'--ro',...
    flowV,vi_body(:,3,2)./flowV,'--b+',...
    flowV,vi_body(:,3,3)./flowV,'--ks',...
    flowV,vi_body(:,3,4)./flowV,'--gx')
title('z-dir')

figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_body(:,1,1)./flowV,'-.ro',...
    flowV,vi_body(:,1,2)./flowV,'-.b+',...
    flowV,vi_body(:,1,3)./flowV,'-.ks',...
    flowV,vi_body(:,1,4)./flowV,'-.gx')
title('x-dir')

figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_body(:,2,1)./flowV,'-.ro',...
    flowV,vi_body(:,2,2)./flowV,'-.b+',...
    flowV,vi_body(:,2,3)./flowV,'-.ks',...
    flowV,vi_body(:,2,4)./flowV,'-.gx')
title('y-dir')


figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_body(:,:,1)./flowV,'-.ro',...
    flowV,vi_body(:,:,2)./flowV,'-.b+',...
    flowV,vi_body(:,:,3)./flowV,'-.ks',...
    flowV,vi_body(:,:,4)./flowV,'-.gx')



%% vi_int_total
figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_int_total(:,3,1)./flowV,'--ro',...
    flowV,vi_int_total(:,3,2)./flowV,'--b+',...
    flowV,vi_int_total(:,3,3)./flowV,'--ks',...
    flowV,vi_int_total(:,3,4)./flowV,'--gx')
title('z-dir')

figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_int_total(:,1,1)./flowV,'-.ro',...
    flowV,vi_int_total(:,1,2)./flowV,'-.b+',...
    flowV,vi_int_total(:,1,3)./flowV,'-.ks',...
    flowV,vi_int_total(:,1,4)./flowV,'-.gx')
title('x-dir')

figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_int_total(:,2,1)./flowV,'-.ro',...
    flowV,vi_int_total(:,2,2)./flowV,'-.b+',...
    flowV,vi_int_total(:,2,3)./flowV,'-.ks',...
    flowV,vi_int_total(:,2,4)./flowV,'-.gx')
title('y-dir')


figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_int_total(:,:,1)./flowV,'-.ro',...
    flowV,vi_int_total(:,:,2)./flowV,'-.b+',...
    flowV,vi_int_total(:,:,3)./flowV,'-.ks',...
    flowV,vi_int_total(:,:,4)./flowV,'-.gx')



figure;
plot(...flowV, flowV./flowV,'k',...
    flowV,vi_int_total(:,:,1)./flowV,'-.ro',...
    flowV,vi_int_total(:,:,2)./flowV,'-.b+',...
    flowV,vi_int_total(:,:,3)./flowV,'-.ks',...
    flowV,vi_int_total(:,:,4)./flowV,'-.gx')


