clear,clc
strFILE = 'inputs/SkyRangerTMotor.txt';

% variables - atmospheric, component geometries, component masses
[seqV, flowTEMP, flowALT, flowRHO, flowMU, flowM, flowR, flowALPHAT, ...
    angCLIMBdeg, angSIDEdeg, numLEADROTOR, geomTypeROTOR, geomNumROTORS,...
    geomDIAMETER, geomNumBLADES, geomARMlength, geomARMradius, ...
    geomBODYheight, geomBODYradius, geomLEGlength, geomLEGradius, ...
    geomLEGcentreradius, geomLEGcentreheight, geomPAYLOADlength, ...
    geomPAYLOADradius, geomPAYLOADheight, geomMOTORheight, ...
    geomMOTORradius, geomHUBheight, geomCGheight, massMOTOR, massARM, ...
    massLEG, massPAYLOAD, massBODY, massVEHICLE] = fcnMVPREAD(strFILE);

% Calculate Reynolds number to CDY database for cylinder and sphere
[cylinderRE, cylinderCDY, sphereRE, sphereCDY] = fcnRECURVE();

% Calculate wetted area of each component
[areaLEG, areaARM, areaBODY, areaPAYLOAD, areaMOTOR] = ...
    fcnCOMPONENTAREA(geomLEGlength, geomLEGradius, geomARMlength, ...
    geomARMradius, geomBODYradius, geomPAYLOADradius, geomPAYLOADlength,...
    geomMOTORradius, geomMOTORheight);

% Create a table with all rotor performance from database
[tabLOOKUP, vecANGLELST] = fcnLOADTABLES(geomTypeROTOR);

[positionROTOR, positionMOTOR, positionARM, positionLEG,...
    positionBODY, positionPAYLOAD] = fcnCOORDSETUP(numLEADROTOR, geomNumROTORS,...
    geomARMlength, geomBODYradius, geomMOTORradius, geomLEGcentreradius, geomLEGcentreheight, ...
    geomPAYLOADheight, geomHUBheight, geomCGheight);

% rotorHUBLOCATIONS = [-0.4020         0   -0.0315;
%          0   -0.4020   -0.0315;
%     0.4020         0   -0.0315;
%          0    0.4020   -0.0315];

% START VELOCITY SEQUENCE
for i = 1:size(seqV,1)
    flowV(i,1) = seqV(i);  
    flowq(i,1) = 0.5*flowRHO*flowV(i,1)^2;    % Calculate the drag of each component
    N = geomNumROTORS;
    
    [powerPARASITIC(i,1), dragVEHICLE(i,1), dragARM(i,1), dragLEG(i,1), dragBODY(i,1), dragMOTOR(i,1),...
            dragPAYLOAD(i,1)] = fcnDRAGPREDICT(geomNumROTORS, flowV(i,1), flowRHO, ...
            flowMU, cylinderRE, cylinderCDY, sphereRE, sphereCDY, areaARM, ...
            areaLEG, areaMOTOR, areaPAYLOAD, areaBODY, geomARMradius, ...
            geomLEGradius, geomMOTORradius, geomPAYLOADradius, geomBODYradius);
    
    [rotorTHRUST1(i,1,:), rotorAngINFLOW, rotorVelINFLOW,...
            rotorRPM, dragBODYinduced(i,1), liftBODY(i,1),...
            pitchVEHICLEdeg(i,1)] = fcnFORCETRIM( flowq(i,1), flowRHO, geomNumROTORS, ...
            geomBODYradius, dragVEHICLE(i,1), massVEHICLE, tabLOOKUP, vecANGLELST );

 
    [vi_int(i,:,:), vi_self(i,:,:), skewRAD(i,:,:), wi, rotorAngINFLOW(i,1,:), rotorVelINFLOW(i,1,:), rotorRPM(i,1,:), rotorPx(i,1,:), rotorPy(i,1,:),...
            rotorMx(i,1,:), rotorMy(i,1,:), rotorCP(i,1,:), rotorCMx(i,1,:), rotorJinf(i,1,:)] = fcnPREDICTRPM(flowq(i,1),flowRHO,...
            geomNumROTORS,geomNumBLADES,geomDIAMETER, positionROTOR,...updated rotor position from rotorRUBlocation 
            rotorTHRUST1(i,1,:),rotorRPM(i,1,:),rotorAngINFLOW(i,1,:),rotorVelINFLOW(i,1,:),...
            pitchVEHICLEdeg(i,1), tabLOOKUP, vecANGLELST);


    [powerROTOR(i,1,:), powerTOTAL(i,1,:), powerVEHICLE(i,1)] = fcnROTORPOWER (flowRHO, geomDIAMETER,...
            geomNumROTORS, rotorCP(i,1,:), rotorRPM(i,1,:), powerPARASITIC(i,1));

    [ momentROTORTHRUST(i,:,:), momentROTORPx(i,:,:), momentROTORPy(i,:,:), ...
            momentROTORMx(i,:,:), momentROTORMy(i,:,:), momentWEIGHTMOTOR(i,:,:),...
            momentWEIGHTARM(i,:,:), momentDRAGMOTOR(i,:,:), momentDRAGARM(i,:,:),...
            momentWEIGHTLEG(i,:,:), momentDRAGLEG(i,:,:), momentWEIGHTBODY(i,:,:),...
            momentWEIGHTPAYLOAD(i,:,:), momentDRAGBODY(i,:,:), momentDRAGPAYLOAD(i,:,:),...
            momentLIFTBODY(i,:,:), momentDRAGBODYinduced(i,:,:), momentTOTAL(i,:) ] ...
            = fcnCALCMOMENTS(massMOTOR, massARM, massLEG, massPAYLOAD, massBODY, ...
            positionROTOR, positionMOTOR, positionARM, ...
            positionLEG, positionBODY, positionPAYLOAD,...
            dragVEHICLE(i,1), dragARM(i,1), dragLEG(i,1), ...
            dragBODY(i,1), dragMOTOR(i,1), dragPAYLOAD(i,1), ...
            dragBODYinduced(i,1), liftBODY(i,1), rotorTHRUST1(i,1,:),...
            rotorPx(i,1,:), rotorPy(i,1,:), rotorMx(i,1,:), ...
            rotorMy(i,1,:),pitchVEHICLEdeg(i,1), geomNumROTORS);
    
  
    [rotorTHRUST(i,1,:), rotorRPM(i,1,:), rotorPx(i,1,:), rotorPy(i,1,:), ...
            rotorMx(i,1,:), rotorMy(i,1,:), rotorCP(i,1,:), rotorCMx(i,1,:), rotorJinf(i,1,:)] ...
            = fcnMOMENTTRIM (rotorTHRUST1(i,1,:), momentTOTAL(i,:,:), positionROTOR,...
            flowV(i,1), flowRHO, pitchVEHICLEdeg(i,1),geomNumROTORS,tabLOOKUP, vecANGLELST);

   

     %add Px convergence(from last time step)
     %make file that generates plots
     
end



