% Thrust lookup test
clear,clc

% Input 
strFILE = 'inputs/3DRvalidation.txt';
% Mass offset with position
massOFFSET = 0; %kg
positionOFFSET = [0, 0, 0]; %on right arm near rotor 2


%GENERAL 
[seqV, flowTEMP, flowALT, flowRHO, flowMU, flowM, flowR, flowALPHAT, ...
    angCLIMBdeg, angSIDEdeg, numLEADROTOR, geomTypeROTOR, geomNumROTORS,...
    geomDIAMETER, geomNumBLADES, geomARMlength, geomARMradius, ...
    geomBODYheight, geomBODYradius, geomLEGlength, geomLEGradius, ...
    geomLEGcentreradius, geomLEGcentreheight, geomPAYLOADlength, ...
    geomPAYLOADradius, geomPAYLOADheight, geomMOTORheight, ...
    geomMOTORradius, geomHUBheight, geomCGheight, massMOTOR, massARM, ...
    massLEG, massPAYLOAD, massBODY, massVEHICLE] = fcnMVPREAD(strFILE);

% New total vehicle mass with offset added
massVEHICLE = massVEHICLE + massOFFSET;

% Calculate Reynolds number to CDY database for cylinder and sphere
[cylinderRE, cylinderCDY, sphereRE, sphereCDY] = fcnRECURVE();


% Calculate wetted area of each component
[areaLEG, areaARM, areaBODY, areaPAYLOAD, areaMOTOR] = ...
    fcnCOMPONENTAREA(geomLEGlength, geomLEGradius, geomARMlength, ...
    geomARMradius, geomBODYradius, geomPAYLOADradius, geomPAYLOADlength,...
    geomMOTORradius, geomMOTORheight);

%TABLE LOAD
[tabLOOKUP, vecANGLELST, vecRPMLST, vecQLST] = testfcnLOADTABLES_THRUST(geomTypeROTOR);

[geomCGoffset]=fcnCGOFFSET(massBODY,massOFFSET,positionOFFSET,geomCGheight);

% Setup coordinates for components
[positionROTOR, positionMOTOR, positionARM, positionLEG,...
    positionBODY, positionPAYLOAD] = fcnCOORDSETUP(numLEADROTOR, geomNumROTORS,...
    geomARMlength, geomBODYradius, geomMOTORradius, geomLEGcentreradius, geomLEGcentreheight, ...
    geomPAYLOADheight, geomHUBheight, geomCGheight, geomCGoffset);

i = 1;

flowq(1,1) = 22.982; % V=23.7m/s
flowV(1,1) = sqrt(flowq(i,1)./0.5*flowRHO);

% Drag of vehicle at q
[powerPARASITIC(1,1), dragVEHICLE(1,1), dragARM(1,1), dragLEG(1,1), dragBODY(1,1),...
            dragMOTOR(1,1), dragPAYLOAD(1,1)] = fcnDRAGPREDICT(geomNumROTORS,...
            flowV(1,1), flowRHO, flowMU, cylinderRE, cylinderCDY, sphereRE, sphereCDY, areaARM, ...
            areaLEG, areaMOTOR, areaPAYLOAD, areaBODY, geomARMradius, ...
            geomLEGradius, geomMOTORradius, geomPAYLOADradius, geomBODYradius);


        
for deltaRPM = -30:15:30
% Set vehicle speed    

% Look up RPM and pitch at force trim condition
[rotorTHRUST(i,1,:), rotorAngINFLOW(i,1,:), rotorVelINFLOW(i,1,:),...
            rotorRPM(i,1,:), dragBODYinduced(i,1), liftBODY(i,1),...
            pitchVEHICLEdeg(i,1)] = fcnFORCETRIM( flowq(1,1), flowRHO, geomNumROTORS, ...
            geomBODYradius, dragVEHICLE(1,1), massVEHICLE, tabLOOKUP, vecANGLELST );

% adjust front rotors ny deltaRPM
 rotorRPM(i,1,1) = rotorRPM(i,1,1)-deltaRPM;
 rotorRPM(i,1,4) = rotorRPM(i,1,4)-deltaRPM;
% adjust rear rotors ny deltaRPM
 rotorRPM(i,1,2) = rotorRPM(i,1,2)+deltaRPM;
 rotorRPM(i,1,3) = rotorRPM(i,1,3)+deltaRPM;

 for n = 1:geomNumROTORS

%LOOKUP THRUST and other rotor forces/moments
[ rotorTHRUST(i,1,n), rotorPx(i,1,n), rotorPy(i,1,n), rotorMx(i,1,n), rotorMy(i,1,n), rotorCP(i,1,n), ...
            rotorCMx(i,1,n), rotorJinf(i,1,n) ] = testfcnTHRUSTLOOKUP( flowq(1,1), flowRHO, ...
            pitchVEHICLEdeg(i,1), rotorRPM(i,1,n), tabLOOKUP, vecANGLELST, vecRPMLST );

end

j = 1;
for pitch = -25:5:25
% take pitching moments with new thrust values
 [ momentROTORTHRUST(i,:,:), momentROTORPx(i,:,:), momentROTORPy(i,:,:), ...
            momentROTORMx(i,:,:), momentROTORMy(i,:,:), momentWEIGHTMOTOR(i,:,:),...
            momentWEIGHTARM(i,:,:), momentDRAGMOTOR(i,:,:), momentDRAGARM(i,:,:),...
            momentWEIGHTLEG(i,:,:), momentDRAGLEG(i,:,:), momentWEIGHTBODY(i,:),...
            momentWEIGHTPAYLOAD(i,:), momentDRAGBODY(i,:), momentDRAGPAYLOAD(i,:),...
            momentLIFTBODY(i,:), momentDRAGBODYinduced(i,:), momentWEIGHTOFFSET(i,:), momentTOTAL(j,:,i) ] ...
            = fcnCALCMOMENTS(massMOTOR, massARM, massLEG, massPAYLOAD, massBODY, massOFFSET, ...
            positionROTOR, positionMOTOR, positionARM, ...
            positionLEG, positionBODY, positionPAYLOAD,positionOFFSET,...
            dragVEHICLE(1,1), dragARM(1,1), dragLEG(1,1), ...
            dragBODY(1,1), dragMOTOR(1,1), dragPAYLOAD(1,1), ...
            dragBODYinduced(i,1), liftBODY(i,1), rotorTHRUST(i,1,:),...
            rotorPx(i,1,:), rotorPy(i,1,:), rotorMx(i,1,:), ...
            rotorMy(i,1,:),pitch, geomNumROTORS);
    j=j+i;
end
clear j
    i=i+1;
       
end